### PR TITLE
Use preventDefault to avoid arrow keys making page scroll

### LINKED ISSUE #13398: Issue with "A basic ray-caster": improvement in the demo
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/A_basic_ray-caster

#### What information was incorrect, unhelpful, or incomplete?
The demo asks to press w, a, s, d keys to navigate. However, the demo works with arrow keys(up, down, left, right) as well. But when up or down keys are pressed entire page scrolls. It's intuitive to use arrow keys to navigate, that's what I did naturally first time.

#### What did you expect to see?
When the demo iframe is in focus entire document shouldn't scroll up and down. And user should be able to interact with the canvas without hassle.<br> Simple fix is to add `evt.preventDefault();` in press(evt) function.<br>
https://mdn.github.io/canvas-raycaster/input.js :
```
function press(evt) {
    evt.preventDefault();   // fix
    var code = evt.keyCode;
    ...
}
```

#### Did you test this? If so, how?
In Chrome 98 on Windows 10

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/canvas_api/a_basic_ray-caster`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/A_basic_ray-caster
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/canvas_api/a_basic_ray-caster/index.md
* Last commit: https://github.com/mdn/content/commit/2279e5ae6c229c707a014a22aa1ec4635a0f981f
* Document last modified: 2021-09-14T18:08:09.000Z

</details>

### PR DESCRIPTION
**Pull request by sideshowbarker**
Fixes https://github.com/mdn/content/issues/13398

### CODE REVIEW

**Comment by sideshowbarker** [comment]
@Elchi3 r?

**Review by Elchi3 — APPROVED** [review]

**Comment by Elchi3** [comment]
I don't have permissions here.

**Comment by sideshowbarker** [comment]
Maybe @ddbeck or @Rumyra can do the merge

**Review by Rumyra — APPROVED** [review]

**Comment by Rumyra** [comment]
Thanks @sideshowbarker 👍

**Pull request merged**
